---
version: 2.1

executors:
  build-executor:
    docker:
      - image: quay.io/labmonkeys/cimg-base:2023.12-22.04.b72

commands:
  make-image:
    description: "Build OCI image and publish from main branch"
    parameters:
      workdir:
        default: "~/project"
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build OCI image and publish from main branch
          command: |
            cd << parameters.workdir >> && pwd
            if git show --name-only --format='' . | grep ""; then
              echo "Changes detected trigger build"
              if [[ "${CIRCLE_BRANCH}" == "main" ]]; then make publish BUILD_VERSION_SUFFIX=".b${CIRCLE_BUILD_NUM}"; else make oci; fi
            else
              echo "No changes in directory << parameters.workdir >> detected, skip build."
            fi
workflows:
  version: 2

  build:
    jobs:
      - alpine:
          context: "Publishing"
      - debian:
          context: "Publishing"
      - rocky:
          context: "Publishing"
      - ubuntu-22-04:
          context: "Publishing"
jobs:
  alpine:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./alpine"

  debian:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./debian"

  rocky:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./rocky"

  ubuntu-22-04:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./ubuntu-22.04"
