---
version: 2.1

executors:
  build-executor:
    docker:
      - image: quay.io/labmonkeys/cimg-base:20.04-20211130.b33

commands:
  make-image:
    description: "Build OCI image and publish from main branch"
    parameters:
      workdir:
        default: "~/project"
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build OCI image and publish from main branch
          command: |
            cd << parameters.workdir >> && pwd
            if [[ "${CIRCLE_BRANCH}" == "main" ]]; then make publish BUILD_VERSION_SUFFIX=".b${CIRCLE_BUILD_NUM}"; else make oci; fi

workflows:
  version: 2

  build:
    jobs:
      - alpine-3-12:
          context: "Publishing"
      - alpine-3-13:
          context: "Publishing"
      - alpine-3-14:
          context: "Publishing"
      - alpine-3-15:
          context: "Publishing"
      - centos-8:
          context: "Publishing"
      - debian-10:
          context: "Publishing"
      - ubuntu-20-04:
          context: "Publishing"
jobs:
  alpine-3-12:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./alpine-3.12"

  alpine-3-13:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./alpine-3.13"

  alpine-3-14:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./alpine-3.14"

  alpine-3-15:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./alpine-3.15"

  centos-8:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./centos-8"
  debian-10:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./debian-10"

  ubuntu-20-04:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./ubuntu-20.04"
